In [ ]:
# 1 convert list to 1-d array
import numpy as np

a = [12.23,13.32,100,36.32]

arr = np.array(a)
print(arr)

[ 12.23  13.32 100.    36.32]


In [6]:
# 2) 3X3 matrix
import numpy as np

arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
# 3) null vector of size 10
import numpy as np
arr = np.zeros(10)
print(arr)
arr[5] = 11
print(arr)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [8]:
# 4) Reverse an array
import numpy as np

arr = np.arange(12,38)

print(arr[::-1])

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [17]:
#5) 2D array with 1 border
import numpy as np
rows = 5
cols = 5
arr = np.zeros((rows,cols), dtype=int)
print(arr)
arr[0,:] =1
arr[-1,:]=1
arr[:,0]=1
arr[:,-1]=1

print(arr)



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [48]:
#6) border with 0
arr = np.ones((3,3))
print(arr)
border = np.zeros((5,5))
border[1:-1,1:-1] = arr
print('\n',border)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# 7) 8X8 Checkboard pattern
import numpy as np


checkerboard = np.zeros((8, 8), dtype=int)


checkerboard[1::2, ::2] = 1  
checkerboard[::2, 1::2] = 1  

print("Checkerboard pattern:")
print(checkerboard)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#list and tuple to array
import numpy as np 

list = [1,2,3,4,5,6,7,8]
tuple = ((8,4,6),(1,2,3))

array_list = np.array(list)
array_tuple = np.array(tuple)

print(array_list)
print(array_tuple)




[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


In [23]:
# 9) append vales in array
import numpy as np

arr = np.array([10,20,30])
n = 40
values = [n + i*10 for i in range (6) ]

appended_array = np.append(arr,values)

print(appended_array)
    









    




[10 20 30 40 50 60 70 80 90]


In [25]:
#10) real and imaginary
com_arr = np.array([ 1.00000000+0.j ,0.70710678+0.70710678j])

real_part = com_arr.real
img_part = com_arr.imag

print(f"real part of the array is {real_part}")
print(f"imaginary part of the array {img_part}")



real part of the array is [1.         0.70710678]
imaginary part of the array [0.         0.70710678]


In [27]:
#11 size of array and length of array

arr = np.array([10,20,30,40,50,60])

print(f"size of array : {len(arr)}")
print(f"length of one array element is: {arr.itemsize}")
print(f"Total bytes consumed by the element of the array :{arr.nbytes}")



size of array : 6
length of one array element is: 8
Total bytes consumed by the element of the array :48


In [28]:
#12 common values in two array 
arr1 = np.array([0,10,20,40,60])
arrr2 = np.array([10,30,40])
print(f"common values between two array:{np.intersect1d(arr1,arrr2)}")




common values between two array:[10 40]


In [29]:
#13) set difference
arr1 = np.array([0,10,20,40,60,80])
arrr2 = np.array([10,30,40,50,70,90])
print(f"set difference between two array:{np.setdiff1d(arr1,arrr2)}")



set difference between two array:[ 0 20 60 80]


In [30]:
#14) set-exclusive
arr1 = np.array([0,10,20,40,60,80])
arrr2 = np.array([10,30,40,50,70])
print(f"Unique values that are in only one(not both) of the array:{np.setxor1d(arr1,arrr2)}")


Unique values that are in only one(not both) of the array:[ 0 20 30 50 60 70 80]


In [32]:
#15) compare two array
a = np.array([1,2])
b = np.array([4,5])

print("a > b")
print(np.greater(a, a))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))





a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [33]:
# Numpy t text file
import numpy as np


array = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Save the array to a text file
np.savetxt("array.txt", array, fmt="%d")  

print("Array saved to 'array.txt'")

Array saved to 'array.txt'


In [35]:
#17) contiguous flattended array
arr = np.array([[10,20,30],[20,40,50]])
arr_flattended = arr.flatten()

print(f"new flattened array :{arr_flattended}")



new flattened array :[10 20 30 20 40 50]


In [37]:
#18) to change data type
arr = np.array([[2,4,6],[6,8,10]])
print(f"Data type of the array arr id:{arr.dtype}")
arr2 = arr.astype(np.float64)
print(f"new type of the array arr id:{arr2.dtype}")



Data type of the array arr id:int64
new type of the array arr id:float64


In [38]:
# 19) 3-d array 
import numpy as np


array_3d = np.eye(3)


print(array_3d)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
#20) array
import numpy as np

# Define the required array
array = np.array([
    [0., 0., 0.],
    [1., 0., 0.],
    [1., 1., 0.],
    [1., 1., 1.]
])

# Print the array
print(array)


[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [40]:
#21) two dimensional array
import numpy as np

# Define the two sample arrays
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])


concatenated_array = np.concatenate((array1, array2), axis=1)


print(concatenated_array)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [41]:
#22) array of shape(3,4)
import numpy as np


original_array = np.arange(12).reshape(3, 4)

print("Original array elements:")
print(original_array)


new_array = original_array * 3

print("\nNew array elements:")
print(new_array)



Original array elements:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [42]:
#23) numpy into python
import numpy as np


array = np.array([[0, 1], [2, 3], [4, 5]])

print("Original array elements:")
print(array)


array_list = array.tolist()

print("\nArray to list:")
print(array_list)




Original array elements:
[[0 1]
 [2 3]
 [4 5]]

Array to list:
[[0, 1], [2, 3], [4, 5]]


In [43]:
#24) with precision 3
import numpy as np


array = np.random.rand(10)  

print("Original array elements:")
print(array)


array_list = array.tolist()


np.set_printoptions(precision=3)

print("\nPrint array values with precision 3:")
print(array)



Original array elements:
[0.58401828 0.91456947 0.3014086  0.15992005 0.86063765 0.41475301
 0.69726742 0.52858054 0.10540245 0.27719942]

Print array values with precision 3:
[0.584 0.915 0.301 0.16  0.861 0.415 0.697 0.529 0.105 0.277]


In [44]:
# 25) scientific notation 
import numpy as np


array = np.array([1.6e-10, 1.6, 1.2e3, 2.35e-1])

print("Original array elements:")
print(array)


np.set_printoptions(suppress=True, precision=3)

print("\nPrint array values with precision 3:")
print(array)


Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [45]:
#26) to add extra column
import numpy as np


array = np.array([[10, 20, 30], [40, 50, 60]])

extra_column = np.array([[100], [200]])  


new_array = np.hstack((array, extra_column))

print(new_array)



[[ 10  20  30 100]
 [ 40  50  60 200]]


In [ ]:
#27) remove specific elements
import numpy as np


array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(array)


indices_to_remove = [0, 3, 4]


new_array = np.delete(array, indices_to_remove)

print("\nDelete first, fourth, and fifth elements:")
print(new_array)




Original array:
[ 10  20  30  40  50  60  70  80  90 100]

Delete first, fourth, and fifth elements:
[ 20  30  60  70  80  90 100]
